# Generated by Django 5.2.3 on 2025-07-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_balance_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
