# Generated by Django 5.2.3 on 2025-07-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_telegramaccount_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='country_code',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
