# Generated by Django 5.2.3 on 2025-07-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_telegramaccount_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccount',
            name='phone_number',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
