# Generated by Django 5.2.3 on 2025-07-30 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_telegramaccount_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='telegram_id',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_accounts', to=settings.AUTH_USER_MODEL),
        ),
    ]
