# Generated by Django 5.2.3 on 2025-08-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_telegramaccount_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='phone_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
