# Generated by Django 5.2.3 on 2025-08-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_telegramaccount_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
