# Generated by Django 5.2.3 on 2025-08-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_telegramaccount_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccount',
            name='telegram_id',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
