# Generated by Django 5.2.3 on 2025-08-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_telegramaccount_telegram_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['telegram_id', 'is_active'], name='users_teleg_telegra_9eafce_idx'),
        ),
    ]
