# Generated by Django 5.2.3 on 2025-09-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_telegramaccount_users_teleg_telegra_9eafce_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telegramaccount',
            name='users_teleg_telegra_e230c0_idx',
        ),
        migrations.AlterField(
            model_name='telegramaccount',
            name='telegram_id',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='telegramaccount',
            index=models.Index(fields=['user', 'is_active'], name='users_teleg_user_id_425807_idx'),
        ),
    ]
