services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
#    env_file:
#      - .env
#    depends_on:
#      - db

#  db:
#    image: postgres:15
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      POSTGRES_DB: ${DB_NAME}
#      POSTGRES_USER: ${DB_USER}
#      POSTGRES_PASSWORD: ${DB_PASSWORD}
#      POSTGRES_HOST: ${DB_HOST}
#    ports:
#      - "5432:5432"
#    env_file:
#      - .env
#
#volumes:
#  postgres_data: