# Generated by Django 5.2.3 on 2025-07-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_gift_transfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='receiver',
        ),
        migrations.AddField(
            model_name='transfer',
            name='email',
            field=models.EmailField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
