# Generated by Django 5.2.3 on 2025-07-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0007_alter_buy_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbuy',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
