# Generated by Django 5.2.3 on 2025-07-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0008_alter_orderbuy_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
