# Generated by Django 5.2.3 on 2025-07-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0009_alter_gift_expires_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('PREMIUM', 'Premium'), ('VIEW', 'View'), ('REACTION', 'Reaction'), ('MEMBER', 'Member')], db_index=True, default='MEMBER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
