# Generated by Django 5.2.3 on 2025-07-26 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0010_vip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='giftusage',
            index=models.Index(fields=['user', 'gift'], name='balance_gif_user_id_35fb59_idx'),
        ),
    ]
