# Generated by Django 5.2.3 on 2025-08-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0011_giftusage_balance_gif_user_id_35fb59_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('som', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rubli', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='buy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
