# Generated by Django 5.2.3 on 2025-08-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0012_currency_alter_buy_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbuy',
            name='currency',
            field=models.CharField(choices=[("SO'M", "so'm"), ('DOLLAR', 'dollar'), ('RUBLI', 'rubli')], default="so'm", max_length=10),
        ),
    ]
