# Generated by Django 5.2.3 on 2025-08-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0014_alter_buy_price_alter_orderbuy_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbuy',
            name='currency',
            field=models.CharField(choices=[("SO'M", "so'm"), ('DOLLAR', 'dollar'), ('RUBLI', 'rubli')], default='DOLLAR', max_length=10),
        ),
    ]
