# Generated by Django 5.2.3 on 2025-07-01 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_service_price_order_service'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServicePrice',
            new_name='Service',
        ),
    ]
