# Generated by Django 5.2.3 on 2025-07-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_country_is_active_link_is_active_service_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
