# Generated by Django 5.2.3 on 2025-07-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_country_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
