# Generated by Django 5.2.3 on 2025-07-22 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_alter_link_is_active_alter_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='kanal_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
