# Generated by Django 5.2.3 on 2025-07-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_link_kanal_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='kanal_name',
            new_name='channel_name',
        ),
    ]
