# Generated by Django 5.2.3 on 2025-07-25 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_ordermember_unique_together'),
        ('service', '0009_alter_country_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='order.order'),
        ),
    ]
