# Generated by Django 5.2.3 on 2025-07-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='member',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
