# Generated by Django 5.2.3 on 2025-07-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
