# Generated by Django 5.2.3 on 2025-07-17 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_ordermember'),
        ('users', '0006_telegramaccount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordermember',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ordermember',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ordermember',
            name='telegram',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.telegramaccount'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ordermember',
            unique_together={('order', 'telegram')},
        ),
    ]
