# Generated by Django 5.2.3 on 2025-07-25 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_alter_order_service_category_alter_order_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordermember',
            unique_together=set(),
        ),
    ]
