# Generated by Django 5.2.3 on 2025-07-25 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_ordermember_unique_together'),
        ('users', '0008_telegramaccount_country_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ordermember',
            index=models.Index(fields=['order', 'user', 'telegram_id'], name='order_order_order_i_8ff62d_idx'),
        ),
    ]
