# Generated by Django 5.2.3 on 2025-07-26 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_ordermember_order_order_order_i_8ff62d_idx'),
        ('users', '0008_telegramaccount_country_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ordermember',
            name='order_order_order_i_8ff62d_idx',
        ),
        migrations.AddField(
            model_name='order',
            name='channel_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='ordermember',
            index=models.Index(fields=['order', 'user', 'telegram'], name='order_order_order_i_8ff62d_idx'),
        ),
    ]
