# Generated by Django 5.2.3 on 2025-07-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_ordermember_order_order_order_i_8ff62d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermember',
            name='day',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordermember',
            name='vip',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
