# Generated by Django 5.2.3 on 2025-07-31 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderFilterCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue', to='order.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order'], name='order_order_order_i_40d567_idx')],
            },
        ),
    ]
