# Generated by Django 5.2.3 on 2025-07-31 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_orderfiltercount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderFilterCount',
        ),
    ]
