# Generated by Django 5.2.3 on 2025-08-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_delete_orderfiltercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
