# Generated by Django 5.2.3 on 2025-08-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
