# Generated by Django 5.2.3 on 2025-08-07 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_order_country_code'),
        ('service', '0013_alter_service_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermember',
            old_name='day',
            new_name='member_duration',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='order_order_status_b4d09f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['is_active', 'created_at'], name='order_order_is_acti_26a2cc_idx'),
        ),
    ]
