# Generated by Django 5.2.3 on 2025-08-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_rename_day_ordermember_member_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number_added',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
