# Generated by Django 5.2.3 on 2025-08-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_number_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='channel_id',
            field=models.IntegerField(default=0),
        ),
    ]
