# Generated by Django 5.2.3 on 2025-08-19 04:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_alter_order_channel_id'),
        ('service', '0013_alter_service_is_active'),
        ('users', '0014_telegramaccount_users_teleg_telegra_9eafce_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_order_status_b4d09f_idx',
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'is_active'], name='order_order_status_03925c_idx'),
        ),
        migrations.AddIndex(
            model_name='ordermember',
            index=models.Index(fields=['user', 'telegram', 'joined_at'], name='order_order_user_id_7b3db9_idx'),
        ),
    ]
